# Use the official PostgreSQL 13 Alpine image as the base image
FROM postgres:13-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres \
    POSTGRES_DB=todoapp

# Expose the PostgreSQL default port
EXPOSE 5432
